require 'rake'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.pattern = 'test/**/test_*.rb'
end

desc 'Run tests.'
task default: :test

desc 'Open an irb session preloaded with this library.'
task :console do
  sh 'irb -I lib/ -r reverse_binary'
end
